### ISSUE TITLE
Sending KeyPresses to other applications called from Hotkey callback

### ISSUE THREAD

**Issue by JostSchenck** [leanflutter/keypress_simulator#2]
I am not sure if what I want to achieve is outside the scope of this plugin: Working on Windows, my app registers a system-wide hotkey (using the package hotkey_manager) to be called to front. The idea is that I can select text in another application, press my hotkey and the app should copy it, paste it into its own data structures and then show a window. To first copy selected text I just want to simulate a Ctrl-V keypress, depending on the other app to offer copy on Ctrl-V. See code below; the `registerHotkeys` function is called from the build method of my App-Widget, which does not seem perfect to me, but it was the only way I could get a riverpod provider reference in there which I need to get access to my apps state.

This approach works only inside my own flutter app -- the app will spring to front when called from other apps, but the copy-to-clipboard will only be performed when I already have my app in front and have text selected in my textfield there.

The code is:

```Future<void> registerHotkeys(WidgetRef ref) async {
  await hotKeyManager.unregisterAll();
  HotKey insertNoteHotKey = HotKey(
    KeyCode.keyW,
    modifiers: [KeyModifier.alt, KeyModifier.control],
    scope: HotKeyScope.system, // Set as inapp-wide hotkey.
  );

  await hotKeyManager.register(
    insertNoteHotKey,
    keyDownHandler: (hotKey) async {
      await keyPressSimulator.simulateKeyPress(
        key: LogicalKeyboardKey.keyC,
        modifiers: [ModifierKey.controlModifier],
      );
      await keyPressSimulator.simulateKeyPress(
        key: LogicalKeyboardKey.keyC,
        modifiers: [ModifierKey.controlModifier],
        keyDown: false,
      );
      windowManager.show(inactive: false);
      FlutterClipboard.paste().then((value) {
        ref.read(newNoteProv).doc = MutableDocument(
          nodes: [
            ParagraphNode(
              id: DocumentEditor.createNodeId(),
              text: AttributedText(text: value),
            ),
          ],
        );
        windowManager.focus();
        windowManager.center(animate: true);
      });
    },
  );
}
```

**Comment by lucasjinreal** [comment]
@JostSchenck I think you can using a background service to do this. 

Simply copy data to clipboard, the using key simulator ctrl v to other window

**Comment by JostSchenck** [comment]
@lucasjinreal Thanks for the hint, I'll look into that. But until now, regarding background services with Flutter I only found resources regarding Android and iOS. I guess anyway what I want to do is out of the scope of this package, so I might as well close this ticket.

**Comment by lucasjinreal** [comment]
However, I just find that even the flutter app itself minimized or into background, the keyboard simulation can still functional on PC.
