### ISSUE TITLE
当应用程序最小化或者不在当前活动窗口下还可以模拟键盘输入吗？

### ISSUE THREAD

**Issue by lucasjinreal** [leanflutter/keypress_simulator#5]
具体来说，想请教两个问题：

1. 当应用程序最小化或者不在当前活动窗口下还可以模拟键盘输入吗？
2. 能否支持任意程序输入窗口的文字键入？例如我现在输入的github的issue文本框

**Comment by lijy91** [comment]
1支持，2可以在任意输入框模拟（模拟复制粘贴快捷键是可以的，其他可以运行示例自行测试）

**Comment by lucasjinreal** [comment]
@lijy91 flutter3.7编译报错，大佬
