### ISSUE TITLE
How to enable access on macOS

### ISSUE THREAD

**Issue by hyungtaecf** [leanflutter/keypress_simulator#8]
I'm trying this package using macOS. It popped up a dialog that I would have to give permission to the app in the Security & Privacy settings but the app doesn't show there (it is a test project I just created running in debug mode). So I couldn't make it work yet. Can someone explain how to do it?

**Comment by lijy91** [comment]
Make sure you have accessibility permissions, and if you still have issues, manually remove and re-add the app
<img width="502" alt="image" src="https://github.com/leanflutter/keypress_simulator/assets/3889523/81dfe17d-88da-4223-b064-15a7f0630ce3">
